### PR TITLE
Allow aiohttp 3.8.0 as required dependency

### PR DESCRIPTION
**Pull request by aquamatthias**
My local tests run fine in this setup.
Maybe we can relax this restriction?

### CODE REVIEW

**Comment by hh-h** [comment]
Hello, sometimes a new version of aiohttp can break this library, so I prefer to limit the upper bound, replace it with `aiohttp>=3.6.2,<3.9.0`

**Comment by aquamatthias** [comment]
@hh-h adjusted.

**Comment by hh-h** [comment]
LGTM! Thank you.

**Comment by hh-h** [comment]
I'm going to release a new version later this week.

**Comment by aquamatthias** [comment]
Awesome. Thanks!

**Pull request merged**
